// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Config struct {
	LogLevel                  *string   `json:"logLevel,omitempty"`
	LogDestinations           []*string `json:"logDestinations,omitempty"`
	LogFile                   *string   `json:"logFile,omitempty"`
	ReadTimeout               *string   `json:"readTimeout,omitempty"`
	WriteTimeout              *string   `json:"writeTimeout,omitempty"`
	ReadBufferCount           *int      `json:"readBufferCount,omitempty"`
	WriteQueueSize            *int      `json:"writeQueueSize,omitempty"`
	UDPMaxPayloadSize         *int      `json:"udpMaxPayloadSize,omitempty"`
	ExternalAuthenticationURL *string   `json:"externalAuthenticationURL,omitempty"`
	API                       *bool     `json:"api,omitempty"`
	APIAddress                *string   `json:"apiAddress,omitempty"`
	Metrics                   *bool     `json:"metrics,omitempty"`
	MetricsAddress            *string   `json:"metricsAddress,omitempty"`
	Pprof                     *bool     `json:"pprof,omitempty"`
	PprofAddress              *string   `json:"pprofAddress,omitempty"`
	RunOnConnect              *string   `json:"runOnConnect,omitempty"`
	RunOnConnectRestart       *bool     `json:"runOnConnectRestart,omitempty"`
	RunOnDisconnect           *string   `json:"runOnDisconnect,omitempty"`
	//  RTSP Server
	Rtsp              *bool     `json:"rtsp,omitempty"`
	RtspDisable       *bool     `json:"rtspDisable,omitempty"`
	Protocols         []*string `json:"protocols,omitempty"`
	Encryption        *string   `json:"encryption,omitempty"`
	RtspAddress       *string   `json:"rtspAddress,omitempty"`
	RtspsAddress      *string   `json:"rtspsAddress,omitempty"`
	RtpAddress        *string   `json:"rtpAddress,omitempty"`
	RtcpAddress       *string   `json:"rtcpAddress,omitempty"`
	MulticastIPRange  *string   `json:"multicastIPRange,omitempty"`
	MulticastRTPPort  *int      `json:"multicastRTPPort,omitempty"`
	MulticastRTCPPort *int      `json:"multicastRTCPPort,omitempty"`
	ServerKey         *string   `json:"serverKey,omitempty"`
	ServerCert        *string   `json:"serverCert,omitempty"`
	AuthMethods       []*string `json:"authMethods,omitempty"`
	//  RTMP Server
	Rtmp           *bool   `json:"rtmp,omitempty"`
	RtmpDisable    *bool   `json:"rtmpDisable,omitempty"`
	RtmpAddress    *string `json:"rtmpAddress,omitempty"`
	RtmpEncryption *string `json:"rtmpEncryption,omitempty"`
	RtmpsAddress   *string `json:"rtmpsAddress,omitempty"`
	RtmpServerKey  *string `json:"rtmpServerKey,omitempty"`
	RtmpServerCert *string `json:"rtmpServerCert,omitempty"`
}

type Group struct {
	Name         *string `json:"name,omitempty"`
	Enabled      *bool   `json:"enabled,omitempty"`
	EnablePublic *bool   `json:"enable_public,omitempty"`
	AllowPublish *bool   `json:"allow_publish,omitempty"`
	AllowRtsp    *bool   `json:"allow_rtsp,omitempty"`
	AllowWebrtc  *bool   `json:"allow_webrtc,omitempty"`
	AllowHls     *bool   `json:"allow_hls,omitempty"`
	//  General
	Paths []*Path `json:"paths,omitempty"`
	//  Authentication
	PublishUser *string `json:"publishUser,omitempty"`
	PublishPass *string `json:"publishPass,omitempty"`
	PublishIPs  *string `json:"publishIPs,omitempty"`
	ReadUser    *string `json:"readUser,omitempty"`
	ReadPass    *string `json:"readPass,omitempty"`
	ReadIPs     *string `json:"readIPs,omitempty"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Path struct {
	Name         *string `json:"name,omitempty"`
	Enabled      *bool   `json:"enabled,omitempty"`
	EnablePublic *bool   `json:"enable_public,omitempty"`
	AllowPublish *bool   `json:"allow_publish,omitempty"`
	AllowRtsp    *bool   `json:"allow_rtsp,omitempty"`
	AllowWebrtc  *bool   `json:"allow_webrtc,omitempty"`
	AllowHls     *bool   `json:"allow_hls,omitempty"`
	Paths        []*Path `json:"paths,omitempty"`
	//  General
	Source                     *string `json:"source,omitempty"`
	SourceFingerprint          *string `json:"sourceFingerprint,omitempty"`
	SourceOnDemand             *bool   `json:"sourceOnDemand,omitempty"`
	SourceOnDemandStartTimeout *string `json:"sourceOnDemandStartTimeout,omitempty"`
	SourceOnDemandCloseAfter   *string `json:"sourceOnDemandCloseAfter,omitempty"`
	MaxReaders                 *int    `json:"maxReaders,omitempty"`
	SrtReadPassphrase          *string `json:"srtReadPassphrase,omitempty"`
	Fallback                   *string `json:"fallback,omitempty"`
	MuxHls                     *bool   `json:"muxHLS,omitempty"`
	//  Record
	Record                *bool   `json:"record,omitempty"`
	RecordPath            *string `json:"recordPath,omitempty"`
	RecordFormat          *int    `json:"recordFormat,omitempty"`
	RecordPartDuration    *string `json:"recordPartDuration,omitempty"`
	RecordSegmentDuration *string `json:"recordSegmentDuration,omitempty"`
	RecordDeleteAfter     *string `json:"recordDeleteAfter,omitempty"`
	//  Authentication
	PublishUser *string `json:"publishUser,omitempty"`
	PublishPass *string `json:"publishPass,omitempty"`
	PublishIPs  *string `json:"publishIPs,omitempty"`
	ReadUser    *string `json:"readUser,omitempty"`
	ReadPass    *string `json:"readPass,omitempty"`
	ReadIPs     *string `json:"readIPs,omitempty"`
	//  Publisher source
	OverridePublisher    *bool   `json:"overridePublisher,omitempty"`
	SrtPublishPassphrase *string `json:"srtPublishPassphrase,omitempty"`
	//  RTSP source
	RtspTransport  *int    `json:"rtspTransport,omitempty"`
	RtspAnyPort    *bool   `json:"rtspAnyPort,omitempty"`
	RtspRangeType  *int    `json:"rtspRangeType,omitempty"`
	RtspRangeStart *string `json:"rtspRangeStart,omitempty"`
	//  Redirect Srouces
	SourceRedirect *string `json:"sourceRedirect,omitempty"`
	//  Hooks
	RunOnInit                  *string `json:"runOnInit,omitempty"`
	RunOnInitRestart           *bool   `json:"runOnInitRestart,omitempty"`
	RunOnDemand                *string `json:"runOnDemand,omitempty"`
	RunOnDemandRestart         *bool   `json:"runOnDemandRestart,omitempty"`
	RunOnDemandStartTimeout    *string `json:"runOnDemandStartTimeout,omitempty"`
	RunOnDemandCloseAfter      *string `json:"runOnDemandCloseAfter,omitempty"`
	RunOnUnDemand              *string `json:"runOnUnDemand,omitempty"`
	RunOnReady                 *string `json:"runOnReady,omitempty"`
	RunOnReadyRestart          *bool   `json:"runOnReadyRestart,omitempty"`
	RunOnNotReady              *string `json:"runOnNotReady,omitempty"`
	RunOnRead                  *string `json:"runOnRead,omitempty"`
	RunOnReadRestart           *bool   `json:"runOnReadRestart,omitempty"`
	RunOnUnread                *string `json:"runOnUnread,omitempty"`
	RunOnRecordSegmentCreate   *string `json:"runOnRecordSegmentCreate,omitempty"`
	RunOnRecordSegmentComplete *string `json:"runOnRecordSegmentComplete,omitempty"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
